exclude: "(.*/)?CITATION.rst$|.*(.fits|.fts|.fit|.header|.txt|tca.*|extern.*|aiapy/extern)$"
repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.23.1
    hooks:
      - id: zizmor
    # This should be before any formatting hooks like isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.8"
    hooks:
      - id: ruff-check
        args: ["--fix", "--unsafe-fixes"]
        types: [python]
        # Define here once and then reference using YAML anchor
        exclude: &exclude_dirs ^aiapy/(data|extern)/
      - id: ruff-format
        types: [python]
        exclude: *exclude_dirs
  - repo: https://github.com/PyCQA/isort
    rev: 8.0.1
    hooks:
      - id: isort
        types: [python]
        exclude: *exclude_dirs
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
        types: [python]
        exclude: *exclude_dirs
      - id: check-case-conflict
        types: [python]
        exclude: *exclude_dirs
      - id: trailing-whitespace
        types_or: [python, rst, yaml, json]
      - id: check-yaml
        types: [yaml]
        exclude: *exclude_dirs
      - id: check-toml
        types: [toml]
        exclude: *exclude_dirs
      - id: debug-statements
        types: [python]
        exclude: *exclude_dirs
      - id: check-added-large-files
        args: ["--enforce-all", "--maxkb=1054"]
      - id: end-of-file-fixer
      - id: mixed-line-ending
  # See https://github.com/python-trio/trio/pull/3255
  -   repo: https://github.com/adhtruong/mirrors-typos
      rev: v1.44.0
      hooks:
      - id: typos
        exclude: *exclude_dirs
ci:
  autofix_prs: false
  autoupdate_schedule: "quarterly"
