version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "mambaforge-latest"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    pre_install:
      - git update-index --assume-unchanged .rtd-environment.yml docs/conf.py
    post_install:
    # Pin numpy for now
     - pip install -U "numpy<2.3.0"

conda:
  environment: .rtd-environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - htmlzip

python:
  install:
    - method: pip
      extra_requirements:
        - docs
      path: .
