default.extend-ignore-identifiers-re = [
    "afile",
    "alog",
    "CPY001",
    "emiss",
    "hsi_",
    "nd",
    "nin",
    "observ",
    "ot",
    "precess",
    "precessed",
    "te",
    "upto",
]
