name: aiapy-dev
channels:
- default
- conda-forge
dependencies:
- python
- numpy
- matplotlib
- astropy
- sunpy
- drms
- flake8
- pytest
- sphinx-astropy
- sphinx
- pip:
  - hissw
  - pytest-remotedata
