[pytest]
minversion = 7.0
testpaths =
    aiapy
    docs
norecursedirs =
    .tox
    build
    docs/_build
    docs/generated
    *.egg-info
    examples
    aiapy/_dev
    .history
doctest_plus = enabled
doctest_optionflags = NORMALIZE_WHITESPACE FLOAT_CMP ELLIPSIS
addopts = --arraydiff --doctest-rst --doctest-ignore-import-errors -p no:unraisableexception -p no:threadexception
remote_data_strict = true
junit_family = xunit1
filterwarnings =
    error
    # Do not fail on pytest config issues (i.e. missing plugins) but do show them
    always::pytest.PytestConfigWarning
    # A list of warnings to ignore follows. If you add to this list, you MUST
    # add a comment or ideally a link to an issue that explains why the warning
    # is being ignored
    # https://github.com/pytest-dev/pytest-cov/issues/557
    # It was fixed and released but it does not seem to be fixed
    ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning
    # Raised by sunpy.coordinates.transformations and will be removed in sunpy 6.1
    ignore:.*module is deprecated, as it was designed for internal use
    # https://github.com/pandas-dev/pandas/issues/54466
    # Should stop when pandas 3.0.0 is released
    ignore:(?s).*Pyarrow will become a required dependency of pandas:DeprecationWarning
    # Zeep relies on deprecated cgi in Python 3.11
    # Needs a release of zeep 4.2.2 or higher
    # https://github.com/mvantellingen/python-zeep/pull/1364
    ignore:'cgi' is deprecated and slated for removal in Python 3.13:DeprecationWarning
    # Can be removed when https://github.com/dateutil/dateutil/issues/1314 is resolved
    # deprecated in Python 3.12, needs a release of dateutil 2.8.3 or higher
    ignore:datetime.datetime.utcfromtimestamp():DeprecationWarning
    # Raised by changing 'seconds' -> 's'
    ignore::astropy.wcs.wcs.FITSFixedWarning
    # SOURCE_UNCERTAINTY_DN = np.sqrt(SOURCE_DATA_DN)
    ignore:invalid value encountered in sqrt:RuntimeWarning
    # The following are raised by the py310-oldestdeps job
    ignore:distutils Version classes are deprecated
    ignore:ERFA function *
