name: CI

on:
  push:
    branches:
      - "main"
      - "*.*"
      - "!*backport*"
    tags:
      - "v*"
      - "!*dev*"
      - "!*pre*"
      - "!*post*"
  pull_request:
  # Allow manual runs through the web UI
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  core:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      submodules: false
      coverage: codecov
      toxdeps: tox-pypi-filter
      posargs: -n auto
      envs: |
        - linux: py312
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      submodules: false
      coverage: codecov
      toxdeps: tox-pypi-filter
      posargs: -n auto
      envs: |
        - windows: py310
        - macos: py311
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  docs:
    needs: [core]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      default_python: "3.12"
      submodules: false
      pytest: false
      toxdeps: tox-pypi-filter
      cache-path: |
        docs/_build/
        docs/generated/
        .tox/sample_data/
      libraries: |
        apt:
          - graphviz
      envs: |
        - linux: build_docs

  online:
    if: "!startsWith(github.event.ref, 'refs/tags/v')"
    needs: [docs]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    with:
      submodules: false
      coverage: codecov
      toxdeps: tox-pypi-filter
      posargs: -n auto --dist loadgroup
      envs: |
        - linux: py312-online
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    # Build wheels when pushing to any branch except main
    # publish.yml will only publish if tagged ^v.*
    if: |
      (
        github.event_name != 'pull_request' && (
          github.ref_name != 'main' ||
          github.event_name == 'workflow_dispatch'
        )
      ) || (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'Run publish')
      )
    needs: [test]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@main
    with:
      python-version: "3.12"
      test_extras: "all,tests"
      test_command: 'pytest -p no:warnings --doctest-rst -m "not mpl_image_compare" --pyargs aiapy'
      submodules: false
    secrets:
      pypi_token: ${{ secrets.pypi_token }}
